#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

; Notes
; We have to use the function version of hotstrings, because some compositions end in ':', which doesn't work well with the static syntax.
; :OC?: tells AHK that we are looking for a string immediately following the last colon with the options O, C, and ?
; O tells AHK that we don't want our ending character, tab, to be included in the replacement. 
; C tells AHK that the string it's looking for is case-sensitive
; ? tells AHK that we want to allow the replacement to occur inside of words. If this were off, you wouldn't be able to do "a<-", and would have to do "a <-" instead.
; TODO some communative and alterative input strings are missing
Hotstring("EndChars", "`t")
Hotstring(":OC?:<-", "←")
Hotstring(":OC?:xx", "×") 
Hotstring(":OC?::-", "÷")
Hotstring(":OC?:*O", "⍟")
Hotstring(":OC?:[-", "⌹")
Hotstring(":OC?:-]", "⌹")
Hotstring(":OC?:OO", "○")
Hotstring(":OC?:77", "⌈")
Hotstring(":OC?:FF", "⌈")
Hotstring(":OC?:ll", "⌊")
Hotstring(":OC?:LL", "⌊")
Hotstring(":OC?:|_", "⊥")
Hotstring(":OC?:TT", "⊤")
Hotstring(":OC?:-|", "⊣")
Hotstring(":OC?:|-", "⊢")
Hotstring(":OC?:=/", "≠")
Hotstring(":OC?:<_", "≤")
Hotstring(":OC?:>_", "≥")
Hotstring(":OC?:==", "≡")
Hotstring(":OC?:=_", "≡")
Hotstring(":OC?:7=", "≢")
Hotstring(":OC?:Z-", "≢")
Hotstring(":OC?:vv", "∨")
Hotstring(":OC?:^^", "∧")
Hotstring(":OC?:^~", "⍲")
Hotstring(":OC?:v~", "⍱")
Hotstring(":OC?:^|", "↑")
Hotstring(":OC?:v|", "↓")
Hotstring(":OC?:cc", "⊂")
Hotstring(":OC?:))", "⊃")
Hotstring(":OC?:c_", "⊆")
Hotstring(":OC?:[|", "⌷")
Hotstring(":OC?:|]", "⌷")
Hotstring(":OC?:A|", "⍋")
Hotstring(":OC?:V|", "⍒")
Hotstring(":OC?:ii", "⍳")
Hotstring(":OC?:i_", "⍸")
Hotstring(":OC?:ee", "∊")
Hotstring(":OC?:e_", "⍷")
Hotstring(":OC?:uu", "∪")
Hotstring(":OC?:nn", "∩")
Hotstring(":OC?:/-", "⌿")
Hotstring(":OC?:\\-", "⍀")
Hotstring(":OC?:,-", "⍪")
Hotstring(":OC?:rr", "⍴")
Hotstring(":OC?:pp", "⍴")
Hotstring(":OC?:O|", "⌽")
Hotstring(":OC?:O-", "⊖")
Hotstring(":OC?:O\\", "⍉")
Hotstring(":OC?:::", "¨")
Hotstring(":OC?:""""", "¨")
Hotstring(":OC?:~:", "⍨")
Hotstring(":OC?:*:", "⍣")
Hotstring(":OC?:oo", "∘")
Hotstring(":OC?:o:", "⍤")
Hotstring(":OC?:O:", "⍥")
Hotstring(":OC?:[]", "⎕")
Hotstring(":OC?:[:", "⍠")
Hotstring(":OC?::]", "⍠")
Hotstring(":OC?:[=", "⌸")
Hotstring(":OC?:=]", "⌸")
Hotstring(":OC?:[<", "⌺")
Hotstring(":OC?:>]", "⌺")
Hotstring(":OC?:T_", "⌶")
Hotstring(":OC?:II", "⌶")
Hotstring(":OC?:o_", "⍎")
Hotstring(":OC?:o-", "⍕")
Hotstring(":OC?:To", "⍕")
Hotstring(":OC?:<>", "⋄")
Hotstring(":OC?:on", "⍝")
Hotstring(":OC?:ww", "⍵")
Hotstring(":OC?:aa", "⍺")
Hotstring(":OC?:VV", "∇")
Hotstring(":OC?:--", "¯")
Hotstring(":OC?:0~", "⍬")